import Head from 'next/head';
import styles from '@/styles/Home.module.css';

export default function Home() {
  const onClickConnectBuilder = () => {
    const getCodeUrl = `https://dkliraer.cafe24api.com/api/v2/oauth/authorize?response_type=code&client_id=${process.env.NEXT_PUBLIC_CAFE24_CLIENT_ID}&state=dkliraer123&redirect_uri=https://cafe24-test.vercel.app/oauth&scope=mall.read_personal,mall.write_personal,mall.read_product`;
    window.location.href = getCodeUrl;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main} onClick={onClickConnectBuilder}>
        cafe24 로그인 !
      </div>
    </>
  );
}
